### ISSUE TITLE
99-8bitdo-bluetooth-controllers.rules still relevant?

### ISSUE THREAD

**Issue by fabiscafe** [paalfe/mixedcontent#2]
Hi. I'd like to ask you if your `99-8bitdo-bluetooth-controllers.rules` are still a thing and if yes if I could use them (with some changes) to put them to https://gitlab.com/Fabish/steam-devices (name is changing to something more generic later). And if this would be OK for you, If you could test them after the merge? :)

Thank you

**Comment by paalfe** [comment]
Go ahead and use them :)
